### ISSUE TITLE
DocumentType not allowed in AdditionalDocumentReference

### ISSUE THREAD

**Issue by rodehoed** [num-num/ubl-invoice#10]
Hi,

When using AdditionalDocumentReference for adding an attachment, it also adds the DocumentType xml key. Although it's empty and does not contain anything it's should not be there. It gives the following warning:

[UBL-CR-114]-A UBL invoice should not include the AdditionalDocumentReference DocumentType

So I think it's best to hide that element when it's not set. https://github.com/num-num/ubl-invoice/blob/a571d8ec525f0b4b1be9e8979731534d80c75e30/src/AdditionalDocumentReference.php#L78

**Comment by rodehoed** [comment]
Im not in the postion todo a PR request atm. The following code below will fix this. But it still gives you the choice to specify **documentType** if you need. If you don't specify it, you have valid UBL output.

```php
    /**
     * The xmlSerialize method is called during xml writing.
     *
     * @param Writer $writer
     * @return void
     */
    public function xmlSerialize(Writer $writer)
    {
        $writer->write([ Schema::CBC .'ID' => $this->id ]);
        if ($this->documentType !== null) {
            $writer->write([
                Schema::CAC . 'DocumentType' => $this->documentType
            ]);
        }
        $writer->write([ Schema::CAC .'Attachment' => $this->attachment ]);     
    }
````

**Comment by brtdv** [comment]
I notice this was fixed in one of the commits of your pull request #13, https://github.com/num-num/ubl-invoice/pull/13/commits/549f7f8158a5024530f89eb5b26b3a2d7b747f7e. Thanks! 👍
