### ISSUE TITLE
Add schemeID class to CompanyID

### ISSUE THREAD

**Issue by rodehoed** [num-num/ubl-invoice#11]
With SI-UBL/PEPPOL the schemeID should be added to the companyID (both supplier and party). Like this:

`<cbc:CompanyID schemeID="0106">12313134</cbc:CompanyID>`

The schemeID comes from: https://docs.peppol.eu/poacc/billing/3.0/codelist/ICD/ and in the above example 106 means the Dutch COC.

**Comment by p1eterdeboer** [comment]
I’ve a fix available for this, but did not do a pull request yet as I’m on a trip.
I can make it available next week.

Pieter

**Comment by brtdv** [comment]
Thank you so much @p1eterdeboer, I've merged your PR #12
