### ISSUE TITLE
PHP 8 Support?

### ISSUE THREAD

**Issue by hanishsingla** [num-num/ubl-invoice#24]
Hi, Are there any plans for compatibility with PHP 8?

**Comment by brtdv** [comment]
Yes absolutely. We haven't implemented support for PHP8 yet because our main stack still uses 7.x, and we don't really have a release date set, but if you want to contribute yourself, feel free to create a push request!

**Comment by brtdv** [comment]
Implemented / updated by @ChristianVermeulen 🙏
See: https://github.com/num-num/ubl-invoice/pull/25
