### ISSUE TITLE
TaxTotal Class doesn't have roundingAmount node

### ISSUE THREAD

**Issue by marwan2** [num-num/ubl-invoice#35]
TaxTotal Class doesn't have roundingAmount node, for example:
```
<cac:TaxTotal>
   <cbc:TaxAmount currencyID="USD">30.00</cbc:TaxAmount>
   <cbc:RoundingAmount currencyID="USD">230.00</cbc:RoundingAmount>
</cac:TaxTotal>
```

Rounding Amount is a total amount of line item.

**Comment by brtdv** [comment]
This is similar to what is being discussed in Issue #32, I will close this Issue
