### ISSUE TITLE
Are you sure that cbc:MultiplierFactorNumeric is restricted to be integer value only?

### ISSUE THREAD

**Issue by ivantcholakov** [num-num/ubl-invoice#44]
![image](https://user-images.githubusercontent.com/1438104/233286625-cdadf12b-b106-47ca-aabf-da0cb73e16db.png)

```php
    /**
     * @return int
     */
    public function getMultiplierFactorNumeric(): ?int
    {
        return $this->multiplierFactorNumeric;
    }

    /**
     * @param int $multiplierFactorNumeric
     * @return AllowanceCharge
     */
    public function setMultiplierFactorNumeric(?int $multiplierFactorNumeric): AllowanceCharge
    {
        $this->multiplierFactorNumeric = $multiplierFactorNumeric;
        return $this;
    }
```
I think it should be a real number. For example, if you have a fixed value discount $35 on an item with net price $456, you have to calculate the corresponding percentage 7.675438596% which is not an integer value.

**Comment by brtdv** [comment]
Hi @ivantcholakov. No, not sure at all. If you want to change this to a float, please submit a PR.
