### ISSUE TITLE
setUBLVersionID not available in version 1.6.2

### ISSUE THREAD

**Issue by DannyWork** [num-num/ubl-invoice#6]
While testing the creation of an xml i got the following error:

Call to undefined method NumNum\UBL\Invoice::setUBLVersionID()

I've added the package with composer and it shows i have version: * 1.6.2
Any idea what went wrong?

**Comment by brtdv** [comment]
Hi @DannyWork 

The setUBLVersionID was not available yet in v1.6.2 of the package. I've pushed a new version update which now includes this functionality. Please update the package to v1.7 or newer, this should fix your issue.
