### ISSUE TITLE
there is no ubl extensions

### ISSUE THREAD

**Issue by brunorbarroso** [num-num/ubl-invoice#9]
This package to support the UBL 2.1 Invoice? Because exists fields not mapped... for example: UBL Extensions... or do i see bad?

**Comment by p1eterdeboer** [comment]
Not all possible UBL fields are included, only the commonly used ones. 
This does not mean you can not generate an UBL 2.1 compatible invoice, because not all fields are mandatory. 
See also the unit test SimpleUBL22InvoiceTest.php for an UBL 2.2 invoice example.

**Comment by brtdv** [comment]
Yes, exactly, what @p1eterdeboer said. Not *all* UBL XML tags are included in the library (yet). Please feel free to add any additional ones you might require. 

The tags that are currently present in the library are the tags that you'll need to generate pretty much ~99% of the most common invoices, including credit notes, invoices with discounts, special vat rates, etc...

**Comment by brunorbarroso** [comment]
OK. Thank you.
I will send a PR containing new fields. Although in my case, I needed more fields, this package was very useful as a basic idea in my project and I believe that many people can still experience this problem and why not, contribute ?! I believe it will be as useful as it was for me.
